### ISSUE TITLE
Phase out "pledge" feature

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securethenews#162]
We've been showing 0 pledges on https://securethe.news/ (AFAICT forever), if the pledge feature is not actually being used, we should probably disable it.

**Comment by conorsch** [comment]
Very much in favor of deleting those code paths. Prior to launch, we'd anticipated that orgs with poor scoring would want a stopgap solution to communicate "We're working on it!", thus the pledge functionality. After launch, response was quite positive, and we've seen a [large uptick in adoption since then](https://securethe.news/blog/how-secure-are-news-sites-report-first-year-secure-news/). 

Much more interested in ramping up integration of additional sites and regions (#143), as well as expanding the grading rubric (#128) than promoting, or even maintaining, the pledge feature.

**Comment by eloquence** [comment]
Alright, I'll take a crack at this one.
