### ISSUE TITLE
consider overrides for sites not using onion-location?  

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securethenews#283]
On twitter it was pointed out by @alecmuffett that at least two big news orgs: BBC and Buzzfeed have onions but _intentionally_ aren't presenting the onion-location header. In this case we need to decide to:

1. Manually override the scan results using an externally maintained mapping of onions->main site URLs like https://github.com/alecmuffett/real-world-onion-sites
2. Be clearer that we're only looking for sites that will present the "onion available" UI element in Tor Browser. Currently this is explained in the About page but that's it.

**Comment by redshiftzero** [comment]
cross linking https://trac.torproject.org/projects/tor/ticket/32256

If the approach of Tor Browser identifying itself to servers is used, then we'll need to use TBselenium (as we do in the SecureDrop functional tests) to look for the presence of Alt-Svc or Onion-Location

**Comment by maeve-fpf** [comment]
From my reading of that issue, it sounds like they would decide to do this identification through User-Agent only (so that CDNs could handle it etc), which the scan could send without needing Selenium or the like. Is it more complicated than that?

**Comment by alecmuffett** [comment]
Hi @maeve-fpf - the User-Agent linked ticket is a proposed RFE and as far as I am aware, no-one is yet working on it.

The tldr of the issue is: Onion-Location headers require effort on the part of sites, to add to all their content. They are optional, and not everyone (especially at the top end) is going to use them.  The RFE might help with that, but still.

**Comment by eloquence** [comment]
@redshiftzero Do you want to work on this one?

One way we discussed in web sync to implement it would be to add either a Boolean "Has onion address" or a string "onion address" field (if we ever want to display the address) to the site model, so that it could be overridden by content editors on a per-site basis.

**Comment by chigby** [comment]
Pinging @redshiftzero again now that this issue is towards the top of the "Ready" column on the web board. Wondering if you had plans to work on this in the near future and/or if you had thoughts on how we might want to implement this (some ideas mentioned in previous comment).

**Comment by chigby** [comment]
Going to start working on this issue using the "string" option outlined above. I think storing/overriding the onion address gives us more flexibility in the event that we want to show the address or, eventually, run tests on the onion service itself (such as it see if we can connect to it).
