### ISSUE TITLE
New news sites receive 0/100 scores

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securethenews#302]
Hi folks, 
Completing #301, I observed that both news sites I added received scores of 0/100 (https://securethe.news/sites/alt-news, https://securethe.news/sites/the-wire), when these scores are incorrect (see the correct results on STN staging). Also, I noticed that I did not have the option to input an onion name on prod, which makes me wonder if an older version of the News Sites form is being used in prod by mistake.

Please let me know if I should provide any more specific information. Thank you!

**Comment by conorsch** [comment]
Well, you're right that prod is a bit behind on deploys, so I'll get that sorted out. Digging into the issue about the 0/100, however, that sounded quite like #285. Testing the versions of the code on staging and prod, I was able unable to catch a scan failure (looks like `altnews.in` is reliably scoring 78/100 currently). 

Turns out it's simply that #225 is still outstanding, @rocodes, and so both the leaderboard and the twitter boat were using stale, uninitialized data. That absolutely should be fixed. For now, I'll re-add the site in prod and trigger a scan on the backend, which should resolve. Apologies for not coordinating more closely with you during the initial update.

**Comment by conorsch** [comment]
Indeed, that's all it was: prod is lagging a bit on the deploy schedule. I re-added the two sites in question, and they're returning accurate scores now:

* https://securethe.news/sites/alt-news
* https://securethe.news/sites/wired

Thanks very much for the super clear reports, @rocodes!
